"""Static integration checks complement, but do not replace, the native build."""
from pathlib import Path
import json
root=Path(__file__).resolve().parents[1]
def read(path):return (root/'raw'/path).read_text()
checks=[]
def check(name,passed):
 checks.append({'check':name,'passed':bool(passed)})
 if not passed:raise AssertionError(name)
ui=read('include/Generator/QuickMenuUI.h');native=read('src/Generator/InGameQuickMenu.cpp');npc=read('src/Loader/DragonWildsNpcLoader.cpp');bridge=read('src/Loader/HelpyNpcAuthoring.inl');guard=read('include/Loader/HelpyNpcGuards.h');catalog=read('src/Loader/QuickMenuCatalog.inl');spawn=read('src/Loader/SpawnTools.inl');fav=read('include/Runtime/F2FavoriteStore.h');plan=read('include/Generator/F2CatalogPlan.h')
check('only requested NPC/resource headings',all(x in ui for x in ['"NPCs & AI"','labelsNpc[]{"NPCS","AI / ENEMIES","FAVORITES"}','labelsResource[]{"TREES","STONE & ORE","FAVORITES"}']))
check('favorites use typed identity and same store','HelpyNodes::FavoriteKey(NodeKind(e,slot),e.id)' in ui and 'ReferencesDirectory()/"Helpy-favorites.json"' in native)
check('old favorites versions accepted', '(document["Version"]!=1&&document["Version"]!=2)' in fav and 'document["Version"]==1?"Path":"Key"' in fav)
check('new favorite file version separates key from path','{"Version",2}' in fav and '{"Key",path}' in fav)
check('NPC snapshots decoded, not flattened into resources','type!="NPC"' in native and 'const int slot=type=="Resource"?2:1;' in native and 'e.nodeKind=type' in native)
check('permission flags travel through live snapshot','e.temporaryAllowed=row.value("TemporaryAllowed",false)' in native and 'e.permanentAllowed=row.value("PermanentAllowed",false)' in native)
check('native classifier checks actual inheritance','npcType&&type->IsChildOf(npcType)' in catalog and '/Script/Dominion.InteractableNPC' in catalog)
check('NPCs recognized before broad resource rules','!npc&&!ai&&!ToolResourceClass' in catalog)
check('reference index supports NPC kind','Kind::Npc' in plan and 'value=="NPC"' in plan)
check('cache placeholders have no spawn permissions', 'Cached path; not yet validated in this world' in catalog and '{"Available",false},{"Loaded",false}' in catalog)
check('explicit NPC branch before permanent clone and actor spawn',spawn.index('action=="DismissHelpyNpcs"')<spawn.index('action=="CreateClone"'))
check('actions execute on existing command path','request["Action"]="DismissHelpyNpcs"' in native and 'SpawnHelpyNpc(*request,world,pawn)' in spawn)
check('authored identity is reselected against live definitions','@runeschema-npc:' in bridge and 'Source NPC is unavailable; refresh the catalogue.' in bridge and 'NPC class changed; select it again.' in bridge)
check('authority is standalone only', 'PS::Network::Detect(world).Mode!=PS::Network::Role::Standalone' in bridge)
check('positive known game-thread ownership required','if(!thread||thread!=GetCurrentThreadId())' in bridge)
check('travel hook required before mutation','m_worldTeardownCallbackId==Hook::ERROR_ID' in bridge)
check('duration JSON bounded before arithmetic conversion',bridge.index('!request["DurationSeconds"].is_number_integer()')<bridge.index('const int seconds=request.value'))
check('NPC auto-batch/power/drops rejected','NPC placement cannot accept AI power, drops, effects or a batch count.' in bridge)
check('source classes and GUID shape checked','GetPathName()!=TEXT("/Script/CoreUObject.Guid")' in guard and 'p->GetSize()!=16' in guard)
check('no guessed save-property memory offsets','GetOffset_Internal()' in guard and 'bSkipSpudStore' in guard)
check('class defaults and archetypes excluded', 'RF_ClassDefaultObject|RF_ArchetypeObject' in guard)
check('exclusion precedes construction completion',npc.index('HelpyNpcGuards::Exclude(pending)')<npc.index('HelpyNpcGuards::VerifyExcluded(actor)'))
check('all /npcs actors are save excluded','SetPersistentVendorId' not in npc and 'HelpyNpcGuards::Exclude(pending);' in npc)
check('construction cannot remove exclusion silently','NPC construction changed its no-save identity' in guard)
check('native lifespan reflected shape validated','ValidateHelpyNpcLifespan' in bridge and 'function->GetParmsSize()!=sizeof(float)' in bridge and 'inputs!=1' in bridge)
check('owned lease uses monotonic time and native backup','std::chrono::steady_clock::now()' in bridge and 'HelpyNpcLifespan(actor,seconds)' in bridge)
check('interactions resolve tracked transient actors','definition->HelpyTemporary?FindHelpyNpc(source->GetWorld(),*definition):FindSpawnedVendor' in npc)
check('legacy persistent shells are migrated by owned magic','words[0]!=VendorIdentity::Magic' in npc and 'QueueLegacyPersistentNpc' in npc)
check('expired leases cannot open shop','lease.Lifetime.Due(HelpyNpcClock())' in bridge and 'Temporary NPC expired while preparing its storefront.' in npc)
check('regular NPC interaction ownership stays checked','source->GetOuterPrivate() != actor' in npc and 'event source is not the vendor\'s unique interaction component' in npc)
check('shared vendor table owner retained','copy->StoreOwner=VendorOffers::Owner(found->ModName,found->Id)' in bridge and 'doc["VendorID"]=source.StoreOwner.substr(6)' in bridge)
check('cleanup never removes shared stores','RemoveCreatedMerchantRows' not in bridge and 'RemoveRow' not in bridge)
check('timed copy cannot inherit a respawn gate','d.SpawnGate.ResetForMap()' in bridge and npc.count('definition.HelpyTemporary || !definition.Enabled')>=3)
check('temporary pending rows excluded from normal scans','!definition.HelpyTemporary && definition.Enabled && definition.SpawnGate.Pending()' in npc)
check('travel retires leases before releasing bindings',npc.index('try {DismissHelpyNpcs();PumpNpcCleanup(1.0);}',npc.index('RuneSchemaVendorWorldTeardown'))<npc.index('ReleaseVendorTracking();',npc.index('RuneSchemaVendorWorldTeardown')))
check('native destruction failures retain existing queue','QueueNpcCleanup(actor); // root/queue first' in bridge and 'keep ownership and retry' in bridge)
check('expired actor does not leave presentation records','m_applied.erase(lease.AppliedKey)' in bridge and 'entry.first.starts_with(lease.ObjectPath+TEXT(":"))' in bridge)
check('remaining NPC cleanup survives unknown exception','another NPC must still be dismissed' in bridge)
check('permanent authoring extends existing allowlist only','value!="npc"' in read('include/Runtime/AuthoredFile.h'))
check('source definition preserved and new document validated','NpcCatalog validate;validate.AddNpc' in bridge and 'Original NPC authoring definition is unavailable.' in bridge)
check('npc authoring has one automatic network mode','"Multiplayer"' not in bridge and '.Multiplayer' not in bridge)
check('no file emission on timed branch','file=std::make_unique<PS::Authoring::StagedFile>("npc",stem,document)' in bridge and 'if(permanent) {\n        document["Location"]' in bridge)
check('failed setup cannot be reported completed','SavedActivationIncomplete' in bridge and 'std::current_exception()' in bridge and 'entry.Enabled=false' in bridge)
check('vanilla spawn permission explicitly closed','row["TemporaryAllowed"]=false;row["PermanentAllowed"]=false' in catalog and 'Vanilla NPCs remain browsable in this cycle.' in bridge)
check('queued dismiss does not claim memory freed','Requested cleanup of ' in spawn and 'permanent/source actors are untouched.' in spawn)
check('the item/binding/audit boundaries remain', not (root/'raw/src/Loader/DragonWildsPlayerLoader.cpp').exists() and not list((root/'raw').rglob('*.bat')))
(root/'verification/source-checks-v10-npc.json').write_text(json.dumps(checks,indent=2)+'\n')
print(f'PASS: {len(checks)} NPC/resource native integration checks (static, not engine execution).')
